# Trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:  
# Actions(s)
jobs:
  qa:
    name: "Quality Assurance"
    runs-on: ubuntu-linux
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7
      - name: "Install python:
        uses: actions/python@v7
        with: '3.14'
      - name: "Install libraries"
        run: pip3 install -r requirements.txt
      - name: "Run tests"
        run: pytest
